services:
  postgres:
    image: postgres:17.9-alpine
    container_name: event-reservation
    restart: unless-stopped
    environment:
      POSTGRES_USER: nishat
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: event_reservation
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=en_US.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent data storage
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Optional initialization scripts
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nishat -d event_reservation"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
